import {openProjects} from './project-store.js';
import {minimumDuration} from './cue-duration.js';
import {mountPNG} from './png-editor.js?v=14';
import {runOpenAI} from './openai-pipeline.js?v=14';
import {tcFrames,makeCues,dsText,utf16} from './core.js';
const $=id=>document.getElementById(id);let cues=[],words=[],other=[],issues=[],busy=false,cancelled=false,worker,rejectWorker,audioURL,controller,rawText='',cloudResult,pngUI,projectId=null,projectCreated=0,audioFile=null,historyLoading=false,saveCount=0,modelPasses=[],mediaSaveError='';
const storePromise=openProjects().catch(e=>{storageError(e);return null;});
function status(text,error=false,progress){$('status').textContent=text;$('status').classList.toggle('error',error);if(Number.isFinite(progress))$('progress').value=progress;checkpoint();}
function setBusy(value){busy=value;for(const id of ['start','file','load','tc','fps','apiKey','rememberKey','clearKey','glossary','context'])$(id).disabled=value;$('cancel').disabled=!value;$('newProject').disabled=value;render();}
function listen(start,end){const audio=$('audio');if(!audio.src){status('בחר את קובץ הקול המקורי כדי להאזין.',true);return;}audio.currentTime=Math.max(0,start-.4);audio.ontimeupdate=()=>{if(audio.currentTime>=end+.4){audio.pause();audio.ontimeupdate=null;}};audio.play().catch(e=>status(e.message,true));}
function render(){try{cues=minimumDuration(cues,Number($('fps').value));for(const c of cues.filter(c=>c.timingAdjusted)){if(!issues.some(i=>i.start===c.start&&i.end===c.end&&i.primary===c.text))issues.push({...c,primary:c.text,alternative:'תזמון הותאם; בדוק מול הקול'});}}catch(e){status(e.message,true);}const host=$('cues');host.replaceChildren();$('raw').textContent=rawText||words.map(w=>w.text).join(' ');$('saveRaw').disabled=!rawText;$('alternative').textContent=other.map(w=>w.text).join(' ');$('export').disabled=busy||!cues.length;$('save').disabled=busy||!cues.length;cues.forEach((c,i)=>{const row=document.createElement('div');row.className='cue';const relevant=issues.filter(x=>x.start<=c.end&&x.end>=c.start);if(relevant.length)row.classList.add('uncertain');const play=document.createElement('button');play.className='secondary';play.textContent='▶ '+(i+1);play.title='האזן לקטע';play.onclick=()=>listen(c.start,c.end);row.append(play);for(const key of ['start','end']){const input=document.createElement('input');input.type='number';input.step='.01';input.min='0';input.value=c[key].toFixed(2);input.disabled=busy;input.setAttribute('aria-label',`${key} ${i+1}`);input.onchange=()=>{c[key]=Number(input.value);render();};row.append(input);}const text=document.createElement('textarea');text.value=c.text;text.disabled=busy;text.setAttribute('aria-label',`כתובית ${i+1}`);text.oninput=()=>{c.text=text.value.replace(/[\r\n]+/g,' ');pngUI.sync();checkpoint();};row.append(text);if(relevant.length){const note=document.createElement('div');note.className='reviewnote';note.textContent='לבדיקה: '+relevant.map(x=>`${x.primary} / ${x.alternative}`).join(' · ');row.append(note);}host.append(row);});pngUI?.sync();checkpoint();}
function download(bytes,name,type){const blob=new Blob([bytes],{type});saveMedia(name,blob).catch(storageError);const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;await checkpoint();await startProject(file.name);audioFile=file;$('filename').textContent=file.name;setAudio(file);const db=await storePromise;if(db)try{await db.audio(projectId,file);}catch(e){storageError(e);}await checkpoint();};
async function timingCache(file,glossary){const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());const key='avid-openai-v1:'+Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('')+':'+glossary;const db=await storePromise;let saved=db?await db.cache(key)||{}:{};return {get:async()=>saved,put:async(name,data)=>{saved[name]=data;if(db)await db.cache(key,saved);}};}

async function decode(file){const context=new AudioContext();let buffer;try{buffer=await context.decodeAudioData(await file.arrayBuffer());}finally{await context.close();}const offline=new OfflineAudioContext(1,Math.ceil(buffer.duration*16000),16000);const mono=offline.createBuffer(1,buffer.length,buffer.sampleRate),channel=mono.getChannelData(0);for(let n=0;n<buffer.numberOfChannels;n++){const source=buffer.getChannelData(n);for(let i=0;i<source.length;i++)channel[i]+=source[i]/buffer.numberOfChannels;}const player=offline.createBufferSource();player.buffer=mono;player.connect(offline.destination);player.start();return (await offline.startRendering()).getChannelData(0);}
$('start').onclick=async()=>{const file=audioFile||$('file').files[0],key=$('apiKey').value.trim();if(!file){status('בחר WAV תחילה.',true);return;}if(!key.startsWith('sk-')){status('הזן מפתח API של OpenAI בשדה המפתח.',true);return;}if(file.size>25*1024*1024){status('לבדיקה זו נדרש קובץ קטן מ־25MB.',true);return;}try{tcFrames($('tc').value,Number($('fps').value));}catch(e){status(e.message,true);return;}cancelled=false;cues=[];words=[];other=[];issues=[];rawText='';cloudResult=null;controller=new AbortController();setBusy(true);try{status('בודק את קובץ הקול…',false,0);const audio=await decode(file);if(audio.length/16000>180)throw Error('גרסת הבדיקה מוגבלת לשלוש דקות אודיו.');if(cancelled)return;const cache=await timingCache(file,JSON.stringify({glossary:$('glossary').value,context:$('context').value}));cloudResult=await runOpenAI({file,key,cache,glossary:$('glossary').value,context:$('context').value,onCheckpoint:async pass=>{modelPasses.push(pass);await checkpoint();},signal:controller.signal,onProgress:text=>status(text),onTranscript:async data=>{rawText=data.text;if(data.words){words=data.words;cues=makeCues(words);issues=cues.map(c=>({...c,primary:'תזמון ראשוני',alternative:'טרם הושלם תיקון'}));}render();await checkpoint();}});cues=cloudResult.cues;words=cloudResult.words;rawText=cloudResult.raw;other=[];issues=cues.filter(c=>c.uncertain||c.timingAdjusted).map(c=>({...c,primary:c.text,alternative:c.timingAdjusted?'תזמון המילה הותאם; בדוק מול הקול':'מודל התיקון סימן ספק'}));render();status(`מוכן — ${cues.length} כתוביות, ${cloudResult.elapsed.toFixed(1)} שניות עיבוד. בדוק את התוצאה מול הקול.${cloudResult.timingRepairs?' חלק מעוגני הזמן הותאמו.':''}${cloudResult.invalidTimingWords?' חלק מעוגני הזמן היו חסרים.':''}`,false,100);}catch(e){if(!cancelled)status(`העיבוד נכשל: ${e.message}${rawText?' התמלול שהתקבל נשמר; ניתן להורידו.':''}`,true);}finally{controller=null;setBusy(false);await checkpoint();if(cancelled)status('הבקשות בוטלו. תוצאה שכבר התקבלה נשמרה.');}};
$('cancel').onclick=()=>{cancelled=true;controller?.abort();$('cancel').disabled=true;status('מבטל את הבקשות…');};
$('saveRaw').onclick=()=>download(rawText,'OpenAI_Transcript.txt','text/plain;charset=utf-8');
const keyStorageName='avid-openai-api-key';
function persistKey(){try{if($('rememberKey').checked){const value=$('apiKey').value.trim();if(value)localStorage.setItem(keyStorageName,value);else localStorage.removeItem(keyStorageName);$('keyNotice').textContent=value?'המפתח נשמר בדפדפן הזה.':'הזן מפתח כדי לשמור אותו.';}else{localStorage.removeItem(keyStorageName);$('keyNotice').textContent='המפתח יימחק ברענון הדף.';}}catch{$('rememberKey').checked=false;$('keyNotice').textContent='הדפדפן חסם שמירה מקומית. המפתח זמין רק בעמוד הנוכחי.';}}
try{const saved=localStorage.getItem(keyStorageName);if(saved){$('apiKey').value=saved;$('rememberKey').checked=true;$('keyNotice').textContent='המפתח השמור נטען מהדפדפן הזה.';}}catch{}
$('rememberKey').onchange=persistKey;
$('apiKey').oninput=persistKey;
$('clearKey').onclick=()=>{$('apiKey').value='';$('rememberKey').checked=false;persistKey();status('המפתח נמחק מהעמוד ומהשמירה בדפדפן.');};
$('export').onclick=()=>{try{cues=minimumDuration(cues,Number($('fps').value));download(utf16(dsText(cues,$('tc').value,Number($('fps').value))),'Avid_SubCap.txt','text/plain;charset=utf-16le');status(issues.length?`הקובץ יוצא. נותרו ${issues.length} הבדלים לבדיקה.`:'הקובץ מוכן לייבוא ל־SubCap.');}catch(e){status(e.message,true);}};
$('save').onclick=()=>download(JSON.stringify({version:2,pngStyle:pngUI.getSettings(),context:$('context').value,glossary:$('glossary').value,tc:$('tc').value,fps:Number($('fps').value),words,cues,other,issues,raw:rawText,usage:cloudResult?.usage,models:cloudResult?.models,elapsed:cloudResult?.elapsed,timingRepairs:cloudResult?.timingRepairs,invalidTimingWords:cloudResult?.invalidTimingWords},null,2),'Avid_SubCap_Project.json','application/json');
$('load').onchange=async()=>{try{const p=JSON.parse(await $('load').files[0].text());if(![1,2].includes(p.version)||![24,25,30,50,60].includes(p.fps)||!Array.isArray(p.cues)||p.cues.length>50000)throw Error('פרויקט לא תקין');await checkpoint();await startProject('פרויקט מיובא');tcFrames(p.tc,p.fps);dsText(p.cues,p.tc,p.fps);$('context').value=p.context||'';if(typeof p.glossary==='string')$('glossary').value=p.glossary;cues=p.cues;rawText=p.raw||'';words=p.words||[];other=p.other||[];issues=p.issues||[];$('tc').value=p.tc;$('fps').value=p.fps;if(p.pngStyle)pngUI.loadSettings(p.pngStyle);render();status('הפרויקט נטען. להאזנה בחר את הקול המקורי.');}catch(e){status(e.message,true);}};

pngUI=mountPNG($('pngEditor'),()=>({id:projectId,cues:busy?[]:minimumDuration(cues,Number($('fps').value)),duration:Number.isFinite($('audio').duration)?$('audio').duration:0,tc:$('tc').value,fps:Number($('fps').value)}),{onChange:()=>checkpoint(),onMedia:saveMedia});
$('openPNG').onclick=()=>{$('pngEditor').scrollIntoView({behavior:'smooth'});};
for(const id of ['tc','fps'])$(id).addEventListener('change',()=>render());

function storageError(e){$('autosave').textContent='השמירה נכשלה: '+(e?.name==='QuotaExceededError'?'האחסון במחשב מלא. הורד פרויקט וגיבוי.':e?.message||'האחסון אינו זמין');$('autosave').classList.add('error');}
function setAudio(file){if(audioURL)URL.revokeObjectURL(audioURL);audioURL=file?URL.createObjectURL(file):null;$('audio').src=audioURL||'';}
function state(){return {id:projectId,createdAt:projectCreated,title:$('projectTitle').value||'פרויקט ללא שם',tc:$('tc').value,fps:Number($('fps').value),context:$('context').value,glossary:$('glossary').value,raw:rawText,words,cues,other,issues,cloudResult,modelPasses,mediaSaveError,png:pngUI?.getState(),status:$('status').textContent,phase:busy?'processing':cloudResult?'done':'draft',fileInfo:audioFile?{name:audioFile.name,type:audioFile.type,size:audioFile.size}:null};}
async function checkpoint(){if(historyLoading||!projectId||!pngUI)return;const snapshot=structuredClone(state()),n=++saveCount;$('autosave').textContent='שומר…';$('autosave').classList.remove('error');const db=await storePromise;if(!db)return;try{await db.save(snapshot);if(n===saveCount&&mediaSaveError){$('autosave').textContent='הפרויקט נשמר; מדיה שלא נשמרה: '+mediaSaveError;$('autosave').classList.add('error');refreshList();}else if(n===saveCount){$('autosave').textContent='נשמר במחשב · '+new Date().toLocaleTimeString('he-IL');refreshList();}}catch(e){storageError(e);}}
async function saveMedia(name,blob,id=projectId){const db=await storePromise;if(!db||!id)throw Error('אין אחסון מקומי זמין לשמירת המדיה');try{await db.media(id,name,blob);if(id===projectId)refreshFiles();await checkpoint();}catch(e){mediaSaveError=name;storageError(e);await checkpoint();throw e;}}
let listTimer;function refreshList(){clearTimeout(listTimer);listTimer=setTimeout(async()=>{const db=await storePromise;if(!db)return;const list=await db.list(),host=$('projectList');host.replaceChildren();for(const p of list){const b=document.createElement('button');b.className='secondary'+(p.id===projectId?' selected':'');b.textContent=p.title;const small=document.createElement('small');small.textContent=`${p.cues?.length||0} כתוביות · ${new Date(p.updatedAt).toLocaleString('he-IL')}`;b.append(small);b.disabled=busy;b.onclick=()=>restoreProject(p.id);host.append(b);}},100);}
let mediaURLs=[];async function refreshFiles(){const db=await storePromise;if(!db||!projectId)return;const id=projectId,files=await db.files(id);if(id!==projectId)return;mediaURLs.forEach(URL.revokeObjectURL);mediaURLs=[];const host=$('savedMedia');host.replaceChildren();for(const f of files.sort((a,b)=>b.savedAt-a.savedAt)){const a=document.createElement('a');a.className='file-link';a.textContent=f.name+' · '+new Date(f.savedAt).toLocaleTimeString('he-IL')+' · '+(f.size/1048576).toFixed(2)+' MB';a.href=URL.createObjectURL(f.blob);mediaURLs.push(a.href);a.download=f.name.split('/').pop();host.append(a);}if(!files.length)host.textContent='מדיה שתפיק תישמר כאן.';}
async function startProject(title='פרויקט חדש'){historyLoading=true;projectId=crypto.randomUUID();projectCreated=Date.now();$('projectTitle').value=title;cues=[];words=[];other=[];issues=[];rawText='';cloudResult=null;modelPasses=[];mediaSaveError='';audioFile=null;setAudio(null);$('file').value='';$('filename').textContent='בחר WAV';$('status').textContent='פרויקט חדש — מוכן לטעינת קובץ.';pngUI.loadState({source:'cues',text:'',style:pngUI.getSettings()});historyLoading=false;render();await checkpoint();refreshFiles();try{localStorage.setItem('avid-last-project',projectId);}catch{}await requestPersistence();}
async function restoreProject(id,revision){if(busy)return;await checkpoint();const db=await storePromise;if(!db)return;const p=revision||await db.get(id);if(!p)return;historyLoading=true;projectId=id;projectCreated=p.createdAt;$('projectTitle').value=p.title;$('tc').value=p.tc;$('fps').value=p.fps;$('context').value=p.context||'';$('glossary').value=p.glossary||'';rawText=p.raw||'';words=p.words||[];cues=p.cues||[];other=p.other||[];issues=p.issues||[];cloudResult=p.cloudResult;modelPasses=p.modelPasses||[];mediaSaveError=p.mediaSaveError||'';const audio=await db.audio(id);audioFile=audio?.blob?new File([audio.blob],p.fileInfo?.name||'audio.wav',{type:p.fileInfo?.type||'audio/wav'}):null;setAudio(audioFile);$('file').value='';$('filename').textContent=audioFile?.name||'בחר WAV';pngUI.loadState(p.png||{style:p.pngStyle});$('status').textContent=p.phase==='processing'?'העיבוד הקודם נעצר. התוצאות שהספיקו להישמר שוחזרו. לחץ תמלול כדי להמשיך מהתוצאות השמורות.':p.status||'הפרויקט שוחזר';historyLoading=false;render();refreshFiles();refreshList();try{localStorage.setItem('avid-last-project',id);}catch{} }
$('savedVersions').parentElement.addEventListener('toggle',async e=>{if(!e.target.open)return;const db=await storePromise;if(!db||!projectId)return;const id=projectId,versions=await db.revisions(id);if(id!==projectId)return;const host=$('savedVersions');host.replaceChildren();for(const v of versions.slice().reverse()){const b=document.createElement('button');b.className='secondary';b.textContent=new Date(v.savedAt).toLocaleString('he-IL')+' · '+(v.state.cues?.length||0)+' כתוביות';b.onclick=()=>restoreProject(id,v.state);host.append(b);}});
let persistenceRequested=false;async function requestPersistence(){if(persistenceRequested)return;persistenceRequested=true;try{const granted=await navigator.storage?.persist?.();$('storageMode').textContent=granted?'שמירה מתמשכת אושרה בדפדפן.':'השמירה מקומית פעילה; הדפדפן לא אישר הגנה מפינוי אוטומטי. מומלץ להוריד גיבוי.';}catch{$('storageMode').textContent='השמירה מקומית. מומלץ להוריד גיבוי.';}}
$('newProject').onclick=async()=>{if(busy)return;await checkpoint();await startProject();};
for(const id of ['projectTitle','context','glossary'])$(id).addEventListener('input',()=>checkpoint());
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')checkpoint();});
(async()=>{document.body.classList.add('has-history');const db=await storePromise;if(!db)return;let id;try{id=localStorage.getItem('avid-last-project');}catch{}const projects=await db.list();if(id&&projects.some(p=>p.id===id))await restoreProject(id);else if(projects.length)await restoreProject(projects[0].id);else await startProject();await requestPersistence();refreshList();})();
