export const HEBREW_MODEL='krivlin/whisper-large-v3-turbo-ivrit-ai-timestamped-onnx';
export const CHECK_MODEL='onnx-community/whisper-large-v3-turbo_timestamped';
export function normalize(text){return text.normalize('NFKC').replace(/[\u0591-\u05C7]/g,'').replace(/[^\p{L}\p{N}]/gu,'').toLowerCase();}
// Word alignment includes insertions and omissions, rather than comparing only word counts.
export function align(a,b){if(Math.max(a.length,b.length)>240&&a.every(w=>Number.isFinite(w.start))&&b.every(w=>Number.isFinite(w.start))){const out=[];const duration=Math.max(a.at(-1)?.end||0,b.at(-1)?.end||0);for(let start=0;start<=duration;start+=22){const aa=a.map((w,i)=>({w,i})).filter(x=>x.w.start>=start&&x.w.start<start+22),bb=b.map((w,i)=>({w,i})).filter(x=>x.w.start>=start&&x.w.start<start+22);out.push(...align(aa.map(x=>x.w),bb.map(x=>x.w)).map(p=>({...p,a:p.a===null?null:aa[p.a].i,b:p.b===null?null:bb[p.b].i})));}return out;}const rows=a.length+1,cols=b.length+1,d=new Uint16Array(rows*cols);for(let i=0;i<rows;i++)d[i*cols]=i;for(let j=0;j<cols;j++)d[j]=j;for(let i=1;i<rows;i++)for(let j=1;j<cols;j++){const same=normalize(a[i-1].text)===normalize(b[j-1].text)&&(!Number.isFinite(a[i-1].start)||!Number.isFinite(b[j-1].start)||Math.abs(a[i-1].start-b[j-1].start)<3);d[i*cols+j]=Math.min(d[(i-1)*cols+j]+1,d[i*cols+j-1]+1,d[(i-1)*cols+j-1]+(same?0:1));}let i=a.length,j=b.length;const out=[];while(i||j){if(i&&j){const same=normalize(a[i-1].text)===normalize(b[j-1].text)&&(!Number.isFinite(a[i-1].start)||!Number.isFinite(b[j-1].start)||Math.abs(a[i-1].start-b[j-1].start)<3);if(d[i*cols+j]===d[(i-1)*cols+j-1]+(same?0:1)){out.push({a:--i,b:--j,same});continue;}}if(i&&d[i*cols+j]===d[(i-1)*cols+j]+1)out.push({a:--i,b:null,same:false});else out.push({a:null,b:--j,same:false});}return out.reverse();}
export function similarity(a,b){const match=align(a,b).filter(x=>x.same).length;return match/Math.max(a.length,b.length,1);}
export function compare(a,b){const issues=[];for(const pair of align(a,b)){if(pair.same)continue;const primary=pair.a===null?null:a[pair.a],alternative=pair.b===null?null:b[pair.b];issues.push({start:primary?.start??alternative.start,end:primary?.end??alternative.end,primary:primary?.text||'—',alternative:alternative?.text||'—'});}return issues;}
export function timedWords(result,offset,duration){const chunks=result.chunks||[];return chunks.filter(c=>/[\p{L}\p{N}]/u.test(c.text)).map((c,i,all)=>{const start=c.timestamp?.[0],end=c.timestamp?.[1]??all[i+1]?.timestamp?.[0]??duration;if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<start||start>duration+.5)throw Error('מודל התמלול החזיר זמני מילים לא תקינים');return {text:c.text.trim(),start:offset+Math.min(duration,start),end:offset+Math.min(duration,Math.max(start+.01,end))};});}
export function regions(issues,duration){const result=[];for(const issue of [...issues].sort((a,b)=>a.start-b.start)){const start=Math.max(0,issue.start-2),end=Math.min(duration,issue.end+2);const last=result.at(-1);if(last&&start<=last.end&&end-last.start<=25)last.end=Math.max(last.end,end);else result.push({start,end});}return result;}
export function reconcile(primary,other,repeated){const output=primary.map(w=>({...w}));const repeats=align(primary,repeated),checks=align(primary,other);const repeatMap=new Map(repeats.filter(p=>p.a!==null).map(p=>[p.a,p]));for(const p of checks){if(p.a===null)continue;const repeat=repeatMap.get(p.a);if(p.b!==null&&repeat?.b!==null&&repeat?.b!==undefined){const candidate=other[p.b],third=repeated[repeat.b];if(normalize(candidate.text)===normalize(third.text)&&normalize(candidate.text)!==normalize(primary[p.a].text)){output[p.a]={...primary[p.a],text:candidate.text};}}}const unresolved=compare(output,other).filter(issue=>{const candidates=repeated.filter(w=>w.end>=issue.start-.4&&w.start<=issue.end+.4);return issue.primary==='—'||!candidates.some(w=>normalize(w.text)===normalize(issue.primary));});return {words:output,issues:unresolved};}
