import {HEBREW_MODEL,CHECK_MODEL,timedWords,compare,regions,reconcile} from './consensus.js';
let pipeline,env,pipe;
let send=(type,data)=>self.postMessage({type,...data}),stopped=()=>false;function check(){if(stopped())throw Error('העיבוד נעצר');}
async function load(model){check();if(pipe){await pipe.dispose();pipe=null;}if(!pipeline){({pipeline,env}=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/dist/transformers.min.js'));env.allowLocalModels=false;env.backends.onnx.wasm.numThreads=self.crossOriginIsolated?Math.min(4,navigator.hardwareConcurrency||2):1;env.backends.onnx.wasm.wasmPaths='https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/dist/';}send('progress',{text:model===HEBREW_MODEL?'טוען את המודל המותאם לעברית…':'טוען את מודל ההשוואה…'});pipe=await pipeline('automatic-speech-recognition',model,{device:'wasm',dtype:model===HEBREW_MODEL?'q8':'q4',progress_callback:p=>send('progress',{text:`מוריד מודל: ${p.file||''}`,progress:p.progress})});}
async function run(audio,start,end,temperature=0){check();const result=await pipe(audio.slice(Math.floor(start*16000),Math.floor(end*16000)),{language:'he',task:'transcribe',return_timestamps:'word',temperature,max_new_tokens:440,condition_on_prev_tokens:false});check();return timedWords(result,start,end-start);}
async function pass(audio,label){const duration=audio.length/16000,result=[];for(let start=0;start<duration;start+=22){const end=Math.min(duration,start+22);send('progress',{text:`${label}: ${Math.round(start)}–${Math.round(end)} שניות מתוך ${Math.round(duration)}`,progress:start/duration*100});const words=await run(audio,Math.max(0,start-2),Math.min(duration,end+2));result.push(...words.filter(w=>(w.start+w.end)/2>=start&&(w.start+w.end)/2<end));if(label==='תמלול עברי')send('partial',{words:result});}return result;}
export async function processAudio(audio,emit,isCancelled=()=>false){send=(type,data)=>emit({type,...data});stopped=isCancelled;try{const duration=audio.length/16000;await load(HEBREW_MODEL);const primary=await pass(audio,'תמלול עברי');if(!primary.length)throw Error('המודל העברי לא זיהה דיבור.');send('primary',{words:primary});let other;try{await load(CHECK_MODEL);other=await pass(audio,'תמלול להשוואה');if(!other.length)throw Error('מודל ההשוואה לא זיהה מילים');}catch(e){send('result',{words:primary,issues:[],warning:`התמלול העברי מוכן, אבל ההצלבה נכשלה: ${e.message}`,compared:false});return;}const firstIssues=compare(primary,other),toCheck=regions(firstIssues,duration);send('comparison',{other,issues:firstIssues});let output=primary,issues=firstIssues;let warning='';if(toCheck.length){await load(HEBREW_MODEL);const repeated=[];for(let i=0;i<toCheck.length;i++){const region=toCheck[i];send('progress',{text:`בודק שוב מול האודיו: קטע ${i+1} מתוך ${toCheck.length}`,progress:i/toCheck.length*100});try{repeated.push(...await run(audio,region.start,region.end,.2));}catch(e){warning=`חלק מהבדיקות החוזרות נכשלו: ${e.message}`;}}const resolved=reconcile(primary,other,repeated);output=resolved.words;issues=resolved.issues;}send('result',{words:output,other,issues,compared:true,warning});}catch(e){send('error',{message:e.message||String(e)});}finally{if(pipe){await pipe.dispose();pipe=null;}}};

if(typeof document==='undefined')self.onmessage=({data})=>processAudio(data.audio,msg=>self.postMessage(msg));
